name: Commit Push Pull Request Branch
on:
  workflow_dispatch:
    inputs:
      PRMsg: 
        description: 'Pull Request Message'
        required: true
        default: 'Pull Request Message'
jobs:
  commitPushPullRequest:
    runs-on: ubuntu-latest
    env:
      BRANCH: ${{ github.ref }}
    steps:
    - name: Initialize mandatory git config
      run: |
       echo $BRANCH
       git config user.name "GitHub Actions"
       git config user.email noreply@github.com
    - name: Add file with version number and name
      run: echo $BRANCH > branch_infos.txt
    - name: Commit changelog and manifest files
      id: make-commit
      run: |
        git add branch_infos.txt
        git commit --message "Commit in branch $BRANCH"
        echo "{commit}={$(git rev-parse HEAD)}" >> $GITHUB_OUTPUT
    - name: Push branch
      run: git push origin $BRANCH
    - name: Create pull request into main
      uses: thomaseizinger/create-pull-request@master
      with:
       github_token: ${{ secrets.GITHUB_TOKEN }}
       head: ${{ github.ref }}
       base: main
       title: ${{ github.ref }} into main
       reviewers: ${{ github.event.issue.user.login }}
       body: |
        ${{ inputs.PRMsg }}
        code commit: ${{ steps.make-commit.outputs.commit }}.
#    - name: Create pull request to develop
#      uses: thomaseizinger/create-pull-request@1.0.0
#      with:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#          github-token: ${{ secrets.GITHUB_TOKEN }}
#          head: release/v${{ github.event.inputs.versionName }}
#          base: develop
#          title: v${{ github.event.inputs.versionName }} into develop
#          reviewers: ${{ github.event.issue.user.login }}
#          body: |
#              Hi!
#              This PR was created in response workflow running.
#              I've updated the version name and code commit: ${{ steps.make-commit.outputs.commit }}.
