name: Create New Branch
on:
  workflow_dispatch:
    inputs:
      branchType:
        description: 'Type of branch'
        required: true
        default: 'test'
        type: choice
        options:
        - test
        - delivery
      branchName:
        description: 'Name of branch  (ie wip)'
        required: true
        default: 'wip'
      branchRelease:
        description: 'Release number (0.1.1)'
        required: true
        default: '0.1.1'

jobs:
  createNewBranch:
    runs-on: ubuntu-latest
    steps:
    - name: Start
      run: |
        echo "Branch: $BRANCH"
      env:
        BRANCH: ${{ inputs.branchType }}/${{ inputs.branchName }}/v${{ inputs.branchRelease }}
    - name: Check out code
      uses: actions/checkout@v3
    - name: Create branch
      run: git checkout -b ${{ env.BRANCH }}
    - name: Initialize mandatory git config
      run: |
       git config user.name "GitHub Actions"
       git config user.email noreply@github.com
    - name: Add file with version number and name
      run: printf 'ext.branch_type = "${{ github.event.inputs.branchType }}"\next.branch_name = "${{ github.event.inputs.branchName }}"\next.release_number = ${{ github.event.inputs.branchRelease }}\n' > branch_infos.txt
    - name: Commit changelog and manifest files
      id: make-commit
      run: |
        git add branch_infos.txt
        git commit --message "Prepare Branch $BRANCH"
        echo "{commit}={$(git rev-parse HEAD)}" >> $GITHUB_OUTPUT
    - name: Push new branch
      run: git push origin $BRANCH
    - name: Create pull request into main
      uses: thomaseizinger/create-pull-request@1.0.0
      with:
       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
       github-token: ${{ secrets.GITHUB_TOKEN }}
       head: $BRANCH
       base: main
       title: $BRANCH into main
       reviewers: ${{ github.event.issue.user.login }}
       body: |
           Hi!
           This PR was created in response workflow running.
           I've updated the release name and code commit: ${{ steps.make-commit.outputs.commit }}.
#    - name: Create pull request to develop
#      uses: thomaseizinger/create-pull-request@1.0.0
#      with:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#          github-token: ${{ secrets.GITHUB_TOKEN }}
#          head: release/v${{ github.event.inputs.versionName }}
#          base: develop
#          title: v${{ github.event.inputs.versionName }} into develop
#          reviewers: ${{ github.event.issue.user.login }}
#          body: |
#              Hi!
#              This PR was created in response workflow running.
#              I've updated the version name and code commit: ${{ steps.make-commit.outputs.commit }}.
