name: Create Release Branch
on:
  workflow_dispatch:
    inputs:
      releaseName:
        description: 'Name of release  (ie 5.5.0)'
        required: true
      releaseCode:
        description: 'Release number (50500)'
        required: true
jobs:
  createrelease:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v3
    - name: Create release branch
      run: git checkout -b release/v${{ github.event.inputs.releaseName }}
    - name: Initialize mandatory git config
      run: |
       git config user.name "GitHub Actions"
       git config user.email noreply@github.com
    - name: Change version number and name
      run: printf 'ext.release_code = ${{ github.event.inputs.releaseCode }}\next.release_name = "${{ github.event.inputs.releaseName }}"\n' > app_releases.gradle
    - name: Commit changelog and manifest files
      id: make-commit
      run: |
        git add app_release.gradle
        git commit --message "Prepare release ${{ github.event.inputs.releaseName }}"
        # echo "::set-output name=commit::$(git rev-parse HEAD)"
        echo "{commit}={$(git rev-parse HEAD)}" >> $GITHUB_OUTPUT
    - name: Push new branch
      run: git push origin release/v${{ github.event.inputs.releaseName }}
    - name: Create pull request into main
      uses: thomaseizinger/create-pull-request@1.0.0
      with:
       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
       github-token: ${{ secrets.GITHUB_TOKEN }}
       head: release/v${{ github.event.inputs.releaseName }}
       base: main
       title: v${{ github.event.inputs.releaseName }} into main
       reviewers: ${{ github.event.issue.user.login }}
       body: |
           Hi!
           This PR was created in response workflow running.
           I've updated the release name and code commit: ${{ steps.make-commit.outputs.commit }}.
#    - name: Create pull request to develop
#      uses: thomaseizinger/create-pull-request@1.0.0
#      with:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#          github-token: ${{ secrets.GITHUB_TOKEN }}
#          head: release/v${{ github.event.inputs.versionName }}
#          base: develop
#          title: v${{ github.event.inputs.versionName }} into develop
#          reviewers: ${{ github.event.issue.user.login }}
#          body: |
#              Hi!
#              This PR was created in response workflow running.
#              I've updated the version name and code commit: ${{ steps.make-commit.outputs.commit }}.
