name: Create New Branch
on:
  workflow_dispatch:
    inputs:
      branchType:
        description: 'Type of branch'
        required: true
        default: 'test'
        type: choice
        options:
        - test
        - delivery
      branchName:
        description: 'Name of branch  (ie wip)'
        required: true
        default: 'wip'
      branchRelease:
        description: 'Release number (0.1.1)'
        required: true
        default: '0.1.1'

jobs:
  createNewBranch:
    runs-on: ubuntu-latest
    env:
      BRANCH: ${{ inputs.branchType }}/${{ inputs.branchName }}/v${{ inputs.branchRelease }}
    steps:
    - name: Check out code
      uses: actions/checkout@v3
    - name: Create branch
      run: git checkout -b $BRANCH
    - name: Initialize mandatory git config
      run: |
       git config user.name "GitHub Actions"
       git config user.email noreply@github.com
    - name: Add file with version number and name
      run: echo $BRANCH > branch_infos.txt
    - name: Commit changelog and manifest files
      id: make-commit
      run: |
        git add branch_infos.txt
        git commit --message "Commit in branch $BRANCH"
        echo "{commit}={$(git rev-parse HEAD)}" >> $GITHUB_OUTPUT
